# Generated by Django 4.1.7 on 2023-05-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_campingpackage_cheappackage_luxurypackage_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
