# Generated by Django 4.1.7 on 2023-05-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_campingpackage_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LuxuryPackage',
            new_name='LuxurayPackage',
        ),
    ]
